### ISSUE TITLE
Build error on MacOS

### ISSUE THREAD

**Issue by charlielidbury** [johnnymn/ocaml-devcontainer#2]
Hello, I'm getting an error at `[dev_container_auto_added_stage_label 2/4] RUN apt-get update`:
```
error: failed to solve: executor failed running [/bin/sh -c apt-get update   && apt-get -y install --no-install-recommends m4   && apt-get autoremove -y   && apt-get clean -y   && rm -rf /var/lib/apt/lists/*]: exit code: 100
[8602 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/kc/q5hc76ns3ns_79lfrqw0sy540000gn/T/devcontainercli/container-features/0.51.3-1697480345956/Dockerfile-with-features -t vsc-ocaml-devcontainer-4dc6a4f2d161a3a90985cd2b1eb11cfc79d247c93280d3a1bd9fb6b6238f37cb --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/charlielidbury/Documents/GitHub/ocaml-devcontainer/.devcontainer
```

Shout if you need more information, not sure what is useful when debugging docker builds.

**Comment by charlielidbury** [comment]
Full error:
```
[+] Building 2.7s (5/7)                                                         
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 1.54kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/ocaml/opam2:4.08                1.0s
 => CACHED [dev_container_auto_added_stage_label 1/4] FROM docker.io/ocam  0.0s
 => ERROR [dev_container_auto_added_stage_label 2/4] RUN apt-get update    1.6s
------                                                                          
 > [dev_container_auto_added_stage_label 2/4] RUN apt-get update   && apt-get -y install --no-install-recommends m4   && apt-get autoremove -y   && apt-get clean -y   && rm -rf /var/lib/apt/lists/*:
#5 0.339 Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
#5 0.376 Get:2 http://deb.debian.org/debian buster InRelease [122 kB]           
#5 0.401 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]  
#5 0.803 Reading package lists...
#5 1.612 E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldoldstable'
#5 1.612 E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldoldstable'
#5 1.612 E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldoldstable-updates'
------
error: failed to solve: executor failed running [/bin/sh -c apt-get update   && apt-get -y install --no-install-recommends m4   && apt-get autoremove -y   && apt-get clean -y   && rm -rf /var/lib/apt/lists/*]: exit code: 100
[8602 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/kc/q5hc76ns3ns_79lfrqw0sy540000gn/T/devcontainercli/container-features/0.51.3-1697480345956/Dockerfile-with-features -t vsc-ocaml-devcontainer-4dc6a4f2d161a3a90985cd2b1eb11cfc79d247c93280d3a1bd9fb6b6238f37cb --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/charlielidbury/Documents/GitHub/ocaml-devcontainer/.devcontainer
[8602 ms]     at BAA (/Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:463:1860)
[8602 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[8602 ms]     at async Ww (/Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:462:1691)
[8602 ms]     at async SK (/Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:462:610)
[8602 ms]     at async SAA (/Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:479:3660)
[8602 ms]     at async GC (/Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:479:4775)
[8603 ms]     at async ZeA (/Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:611:12251)
[8603 ms]     at async VeA (/Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:611:11992)
[8610 ms] Exit code 1
[8613 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/charlielidbury/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/charlielidbury/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-645ec2ff-3bca-44e5-af0a-928b61d9d20e1697480339641 --workspace-folder /Users/charlielidbury/Documents/GitHub/ocaml-devcontainer --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/charlielidbury/Documents/GitHub/ocaml-devcontainer --id-label devcontainer.config_file=/Users/charlielidbury/Documents/GitHub/ocaml-devcontainer/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/charlielidbury/Documents/GitHub/ocaml-devcontainer/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[8613 ms] Exit code 1
[11407 ms] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f636861726c69656c6964627572792f446f63756d656e74732f4769744875622f6f63616d6c2d646576636f6e7461696e6572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f636861726c69656c6964627572792f446f63756d656e74732f4769744875622f6f63616d6c2d646576636f6e7461696e65722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f636861726c69656c6964627572792f446f63756d656e74732f4769744875622f6f63616d6c2d646576636f6e7461696e65722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f636861726c69656c6964627572792f446f63756d656e74732f4769744875622f6f63616d6c2d646576636f6e7461696e65722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/workspaces/ocaml-devcontainer'
    at r.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:11397)
    at async r.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:13603)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1861:2796
    ```
